# Generated by Django 5.2.10 on 2026-01-21 09:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cmc_id', models.IntegerField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_stablecoin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('decimals', models.IntegerField(default=8)),
            ],
            options={
                'verbose_name_plural': 'Cryptocurrencies',
                'indexes': [models.Index(fields=['symbol'], name='balance_cry_symbol_20a024_idx'), models.Index(fields=['is_active', 'symbol'], name='balance_cry_is_acti_92f818_idx')],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('binance', 'Binance'), ('bybit', 'Bybit'), ('kucoin', 'KuCoin'), ('okx', 'OKX'), ('coinbase', 'Coinbase'), ('huobi', 'Huobi'), ('gate', 'Gate.io'), ('mexc', 'MEXC'), ('bitget', 'Bitget')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('api_docs_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supports', models.JSONField(default=list)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'is_active'], name='balance_exc_name_826c83_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('default_currency', models.CharField(default='USD', max_length=10)),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('groups', models.ManyToManyField(blank=True, related_name='balance_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='balance_user_permissions', to='auth.permission')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('user'), models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserExchangeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('api_key', models.CharField(max_length=500)),
                ('api_secret', models.CharField(max_length=500)),
                ('api_passphrase', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('syncing', 'Syncing')], max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.exchange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_connections', to='balance.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='balance_use_email_a727bb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='balance_use_usernam_e4f8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='userexchangeconnection',
            index=models.Index(fields=['user', 'is_active'], name='balance_use_user_id_9d744e_idx'),
        ),
        migrations.AddIndex(
            model_name='userexchangeconnection',
            index=models.Index(fields=['last_sync_at'], name='balance_use_last_sy_69fb1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userexchangeconnection',
            unique_together={('user', 'exchange', 'nickname')},
        ),
    ]
