# Generated by Django 5.2.10 on 2026-01-24 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('available_amount', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('locked_amount', models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True)),
                ('price_at_snapshot', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('usd_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('snapshot_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.cryptocurrency')),
                ('exchange_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='balance.userexchangeconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'cryptocurrency', '-snapshot_time'], name='balance_bal_user_id_e97a48_idx'), models.Index(fields=['user', '-snapshot_time'], name='balance_bal_user_id_5865ba_idx'), models.Index(fields=['exchange_connection', '-snapshot_time'], name='balance_bal_exchang_cc22f8_idx')],
            },
        ),
    ]
