# Generated by Django 5.2.10 on 2026-01-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_balancesnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
