# Generated by Django 5.2.10 on 2026-01-25 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_alter_cryptocurrency_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_btc', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(default='coingecko', max_length=50)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='balance.cryptocurrency')),
            ],
            options={
                'verbose_name_plural': 'Price Histories',
                'indexes': [models.Index(fields=['cryptocurrency', '-timestamp'], name='balance_pri_cryptoc_bb5617_idx'), models.Index(fields=['timestamp'], name='balance_pri_timesta_094bbd_idx')],
                'unique_together': {('cryptocurrency', 'timestamp')},
            },
        ),
    ]
