# Generated by Django 5.2.10 on 2026-01-31 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_pricehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancesnapshot',
            options={'verbose_name_plural': 'Снимки балансов'},
        ),
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'verbose_name_plural': 'Криптовалюты'},
        ),
        migrations.AlterModelOptions(
            name='exchange',
            options={'verbose_name_plural': 'Биржи'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name_plural': 'История цен'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userexchangeconnection',
            options={'verbose_name_plural': 'Подключения'},
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_value_btc', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('total_invested_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('top_coins', models.JSONField(default=list)),
                ('exchange_allocation', models.JSONField(default=dict)),
                ('snapshot_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-snapshot_time'], name='balance_por_user_id_620b1d_idx'), models.Index(fields=['snapshot_time'], name='balance_por_snapsho_c57c9c_idx')],
            },
        ),
    ]
