# Generated by Django 5.2.10 on 2026-01-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0005_alter_balancesnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliosnapshot',
            options={'verbose_name_plural': 'Снимки портфелей'},
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='exchange_allocation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='top_coins',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
