# Generated by Django 5.2.10 on 2026-01-31 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_alter_portfoliosnapshot_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWalletConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('syncing', 'Syncing')], max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Подключения кошельков',
                'indexes': [models.Index(fields=['user', 'is_active'], name='balance_use_user_id_df5880_idx'), models.Index(fields=['last_sync_at'], name='balance_use_last_sy_a19c5c_idx')],
                'unique_together': {('user', 'network', 'address')},
            },
        ),
    ]
