# Generated by Django 5.2.10 on 2026-02-01 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0007_userwalletconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
                ('chain_id', models.IntegerField()),
                ('native_coin', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Сети',
                'db_table': 'blockchain_networks',
            },
        ),
        migrations.AlterField(
            model_name='userwalletconnection',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balance.blockchainnetwork'),
        ),
    ]
