# Generated by Django 5.2.10 on 2026-02-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0008_blockchainnetwork_alter_userwalletconnection_network'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='balancesnapshot',
            name='balance_bal_exchang_cc22f8_idx',
        ),
        migrations.RemoveField(
            model_name='balancesnapshot',
            name='available_amount',
        ),
        migrations.RemoveField(
            model_name='balancesnapshot',
            name='exchange_connection',
        ),
        migrations.RemoveField(
            model_name='balancesnapshot',
            name='locked_amount',
        ),
        migrations.RemoveField(
            model_name='balancesnapshot',
            name='price_at_snapshot',
        ),
        migrations.AddIndex(
            model_name='balancesnapshot',
            index=models.Index(fields=['-snapshot_time'], name='balance_bal_snapsho_83bfbd_idx'),
        ),
    ]
